### ISSUE TITLE
"Encrypting and Decrypting with an RSA Key Pair" Example uses keys in reversed

### ISSUE THREAD

**Issue by kyleoliveira** [awsdocs/aws-cloudhsm-user-guide#1]
The [Encrypting and Decrypting with an RSA Key Pair Example](https://docs.aws.amazon.com/cloudhsm/latest/userguide/java-sample-asymmetric-encrypt-decrypt.html) uses the private key to encrypt and public key to decrypt. It should be the opposite (e.g. public key for encryption).

**Comment by singnikhil** [comment]
I've given two examples in main:
1. Encrypt with private key and decrypt with public key
2. Encrypt with public key and decrypt with private key

The former provides authentication, and latter provides encryption.

**Comment by mattsb42-aws** [comment]
Well that's awkward... I'll make sure the document owners see this.

**Comment by pettibon** [comment]
Thanks much. GitHub has been updated with the latest change from Nikhil.
