### ISSUE TITLE
Java KeyManagement example does not compile

### ISSUE THREAD

**Issue by iay** [awsdocs/aws-cloudhsm-user-guide#11]
The following code does not compile:

```java
// Import the key as extractable and persistent.
// You can use the key handle to identify the key in other operations.
long importedKeyHandle = importKey(keyToBeImported, "Test", true, true);
System.out.println("Imported Key Handle : " + importedKeyHandle);
```

The reason for this is that the local `importKey` method is specified as `void`, not as returning a `long`.

`importKey` in turn calls `ImportKey.importKey(key, spec);` but this returns a `Key`, not a handle.

In addition, this code:

```java
KeyGenerator kg = KeyGenerator.getInstance("AES");
```

... does not compile because of an uncaught checked exception.

**Comment by joneps** [comment]
Hi @iay!
I see that this is an older issue, but just so you know, we've recently updated and refined our Java sample docs. I'm going to go ahead and close this issue for now.
