### ISSUE TITLE
No download links provided for version 1.1.1 (except Amazon Linux)

### ISSUE THREAD

**Issue by dmjones** [awsdocs/aws-cloudhsm-user-guide#12]
The links for version 1.1.1 of the software are missing, throughout the documentation.

On https://docs.aws.amazon.com/cloudhsm/latest/userguide/client-history.html, only the Amazon Linux link appears to point to a 1.1.1 release. The rest still point to 1.1.0-2.

The same is true on https://docs.aws.amazon.com/cloudhsm/latest/userguide/install-and-configure-client-linux.html.

**Comment by joneps** [comment]
Hi @dmjones, 
Thanks so much for catching this! It appears there was a disconnect between the entities we use for doc shorthand in a previous version. I've gone ahead and fixed the issue.
Best,
Jonathan
