### ISSUE TITLE
How to migrate from Safenet Luna to CloudHSM?

### ISSUE THREAD

**Issue by pramodshinde** [awsdocs/aws-cloudhsm-user-guide#15]
Hey I am currently using Safenet Luna client with PKCS11 library, We are using pin and label mechanism to fetch classic hsm keys. Now we are thinking to migrate to CloudHSM with same library. Is there any official guild for migration of classic keys to CloudHSM?
Thanks.

**Comment by chetansanghiwork** [comment]
Please let know if there was response or information for the above question.

**Comment by pramodshinde** [comment]
@chetansanghiwork If I remember exactly we installed both libraries and decrypted with old HSM version and encrypted with 
HSM version, using new HSM keys. kinda data decrypted and encrypted again.

**Comment by gmudambi** [comment]
The following official guide is intended to assist developers who are upgrading to CloudHSM from CloudHSM Classic.

[https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/Docs/CloudHSMUpgradeGuide-latest.pdf](https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/Docs/CloudHSMUpgradeGuide-latest.pdf)
