### ISSUE TITLE
nginx cannot load cloudhsm ssl_engine

### ISSUE THREAD

**Issue by lacabra** [awsdocs/aws-cloudhsm-user-guide#17]
The issue seems to be related to #8, but the solutions proposed there don't resolve the problem.

The EC2 host is running Ubuntu 16.04:
```
$ uname -a
Linux 4.4.0-1069-aws #79-Ubuntu SMP Mon Sep 24 15:01:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

The OpenSSL shared library is installed and working fine:
```
$ openssl engine -t cloudhsm
(cloudhsm) CloudHSM hardware engine support
     	SDK Version: 2.03
[ available ]
```
although it is not displayed in the list of available engines:
```
$ openssl engine -t
(rdrand) Intel RDRAND engine
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]
```

And `nginx` cannot load it as nginx fails to launch with the following line in `/etc/nginx/nginx.conf`:
```
ssl_engine cloudhsm;
```

with the following error:
```
$ cat /var/log/nginx/error.log
2018/10/17 22:05:15 [emerg] 31975#31975: ENGINE_by_id("cloudhsm") failed (SSL: error:260B606D:engine routines:DYNAMIC_LOAD:init failed error:2606A074:engine routines:ENGINE_by_id:no such engine:id=cloudhsm)
```

I've tried loading the engine dynamically, and add it to the list of available engines with: 
```
$ openssl engine -vvvv dynamic -pre SO_PATH:/opt/cloudhsm/lib/libcloudhsm_openssl.so -pre ID:cloudhsm -pre LIST_ADD:1 -pre LOAD
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/opt/cloudhsm/lib/libcloudhsm_openssl.so
[Success]: ID:cloudhsm
[Success]: LIST_ADD:1
[Success]: LOAD
Loaded: (cloudhsm) CloudHSM hardware engine support
```

The command succeeds, but it does not make a difference, and `cloudhsm` is still not included in the list of available engines.

Any suggestions on how `nginx` can load the `cloudhsm` module?

**Comment by lacabra** [comment]
I have resolved my own issue, and I'm documenting it here for future reference.

The underlying issue is that the environment in which the webserver (`nginx`) executes needs to have access to the `cloudhsm-client` credentials in order to load the SSL accelerator (`ssl_engine`) and offload SSL routines to CloudHSM.

Even when you log into your host with your regular user and everything works for that user (`openssl engine -t cloudhsm`) that does not mean that it will also work for the user that runs the webserver (`root` in this case), and that needs to be configured separately. To illustrate this point run:
```
$ sudo openssl engine -t cloudhsm
environment variable n3fips_password is not set
Dynamic Engine: cloudhsm load failed 
140432174429848:error:260B606D:engine routines:DYNAMIC_LOAD:init failed:eng_dyn.c:545:
140432174429848:error:2606A074:engine routines:ENGINE_by_id:no such engine:eng_list.c:390:id=cloudhsm
```
And you see a more verbose output like the one-liner that appears on `/var/log/nginx/error.log`. Compare it to the following command where the current environment is passed onto sudo:
```
$ sudo -E openssl engine -t cloudhsm
(cloudhsm) CloudHSM hardware engine support
     	SDK Version: 2.03
[ available ]
```
If your output to the above command throws an error, review the section 
[Install and Use the AWS CloudHSM Dynamic Engine for OpenSSL](https://docs.aws.amazon.com/cloudhsm/latest/userguide/openssl-library-install.html), and make sure that `n3fips_password` is set in your environment (step 3).

Changing the sudo environment only helps us troubleshoot the problem, but does not solve the underlying problem, as the credentials need to be loaded into the environment that loads the webserver, which is not sudo.

Furthermore, the instructions from AWS CLoudHSM on [Configuring the Web Server](https://docs.aws.amazon.com/cloudhsm/latest/userguide/ssl-offload-configure-web-server.html) assume that the host runs  `systemd` as the init system. In my case, my host machine is running `init` and so the documented configuration was not being picked up. It further exacerbates this issue the fact that many packages (including `nginx`) install configuration files for both init systems, so it's not easy to tell which one is active. See [this post](https://unix.stackexchange.com/a/164092/297701) to figure out what init system your host is running.

Assuming that you followed up to step 9 in [this guide](https://docs.aws.amazon.com/cloudhsm/latest/userguide/ssl-offload-configure-web-server.html), the missing part is to edit `/etc/init/nginx.conf` to the following:
```
description "nginx - small, powerful, scalable web/proxy server"

start on filesystem and static-network-up
stop on runlevel [016]

expect fork
respawn

pre-start script
	. /etc/sysconfig/nginx
	[ -x /usr/sbin/nginx ] || { stop; exit 0; }
	/usr/sbin/nginx -q -t -g 'daemon on; master_process on;' || { stop; exit 0; }
end script

script
	. /etc/sysconfig/nginx
	/usr/sbin/nginx -g 'daemon on; master_process on;'
end script

pre-stop exec /usr/sbin/nginx -s quit
``` 
Please note that loading the credentials needs to be present on both the `pre-start script` which tests nginx configuration files (and would otherwise fail) and `script` which is the stanza that actually launches `nginx`.

Hope this helps others 👍

**Comment by pradeepkondaveti** [comment]
@lacabra Thanks for the valuable information. Followed your guide and made changes accordingly.

But unfortunately I am not able to resolve the same issue on my RHEL with NGINX.
After setting the ENV vars I am getting SUCCESS result for openssl 

`openssl engine -t cloudhsm`

```
(cloudhsm) CloudHSM hardware engine support
     	SDK Version: 2.03
[ available ]
```

But with NGINX still i am getting following ERROR:


```
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has begun starting up.
Feb 28 08:59:55  nginx[7924]: environment variable n3fips_password is not set
Feb 28 08:59:55 [7924]: nginx: [emerg] ENGINE_by_id("cloudhsm") failed (SSL: error:260B606D:engine routines:DYNAMIC_LOAD:init failed error:2606A074:engine 
Feb 28 08:59:55  nginx[7924]: Dynamic Engine: cloudhsm load failed
Feb 28 08:59:55  systemd[1]: nginx.service: control process exited, code=exited status=1
Feb 28 08:59:55  systemd[1]: Failed to start nginx - high performance web server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has failed.
```
Plz let me know if anything is missing myside.

**Comment by pradeepkondaveti** [comment]
In my case it's RHEL and systemd is loading the configuration.

setting Environment variable for  `n3fips_password` in `/lib/systemd/system/nginx.service`  is solved my issue and NGINX is now loading cloudhsm ssl engine :)

**Comment by oceanlazy** [comment]
Anyway if I add `Environment="n3fips_password=example_user:testpass"` to /lib/systemd/system/nginx.service I get `environment variable n3fips_password is not set`

Update: As temporary solution I added `Defaults env_keep += "n3fips_password"` to `sudo visudo`.

**Comment by ZachMurray** [comment]
I'm new to nginx and AWS CloudHSM and having this issue. 

I'm getting issue with an unknown variable ls_openssl_conf and "no such engine". 

``` 
$ sudo service nginx start

Starting nginx: environment variable ls_openssl_conf is not set
Conf file is not set or unavailable, continuing with default
environment variable n3fips_password is not set
Dynamic Engine: cloudhsm load failed
nginx: [emerg] ENGINE_by_id("cloudhsm") failed (SSL: error:260B606D:engine routines:DYNAMIC_LOAD:init failed error:2606A074:engine routines:ENGINE_by_id:no such engine:id=cloudhsm)
                                                          [FAILED]
```

**Comment by AndyShortt** [comment]
I encountered the same errors outlined in this issue. After attempting to set the n3fips_password environment variable in many locations, I finally found that Amazon Linux (2018.03) is using **init** and not **systemd** to start the service. Adding the export statement to the start() block of /etc/init.d/nginx successfully loaded the variable at run time for me.
