### ISSUE TITLE
Typo on CloudHSM Landing Page

### ISSUE THREAD

**Issue by jsbonso** [awsdocs/aws-cloudhsm-user-guide#18]
In the CloudHSM landing page, you have a minor typo: 
https://aws.amazon.com/cloudhsm/

Secure key storage in tamper-**resistent** hardware available in multiple Availability Zones (AZs)

It should be: tamper-**resistant**

**Comment by dmryan123** [comment]
Hello,

Thank you for taking the time to submit feedback on our documentation. The error has been fixed and public documentation has been updated. 

All best, 
David Ryan
