### ISSUE TITLE
SDK Getting started

### ISSUE THREAD

**Issue by howardkitto** [awsdocs/aws-cloudhsm-user-guide#19]
Could you create a guide as to how to get started writing apps using the CloudHSM SDK? (especially the Go version). It's really hard to know where to begin, for example how to set up a VPN so that I can write code that can access an HSM that is tucked away inside a private subnet in a VPC.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking the time to submit feedback on our documentation. While a guide for writing apps is not currently something we are working on, we have reviewed your request and will consider potentially implementing it.  

All best, 
David Ryan
