### ISSUE TITLE
Cfm2LoginHSM returned 206  HSM Error: This user doesn't exist

### ISSUE THREAD

**Issue by solodino** [awsdocs/aws-cloudhsm-user-guide#20]
I completed the setup for CloudHSM and installed the CloudHSM client. I was able to log in CloudHSM and changed PRECO to CO and created another CO. But when I tried to load cloudhsm in OpenSSL (openssl engine -t cloudhsm), it gave me the following error message:
"(cloudhsm) CloudHSM hardware engine support
        SDK Version: 2.03
Cfm2LoginHSM returned 206  HSM Error: This user doesn't exist
[ unavailable ]"

Any suggestion would be appreciated.

**Comment by prgun** [comment]
This could happen when the openssl engine expecting a Crypto User (CU) but configured user was Crypto Officer (CO). try changing to CU.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. It sounds like you actually have a technical support question. If you have [signed up for technical support](https://aws.amazon.com/premiumsupport/), I recommend contacting [technical support](https://aws.amazon.com/contact-us/) for this. You can also post this question on [AWS re:Post](https://repost.aws/), which is a good resource for questions and answers (Q&A).

 All best,
 David Ryan
