### ISSUE TITLE
Customer needs root user instead of AWS root account to copy the certificate to the right location

### ISSUE THREAD

**Issue by lucasmr11** [awsdocs/aws-cloudhsm-user-guide#21]
Documentation [Install and Configure the AWS CloudHSM Client (Linux)](doc_source/install-and-configure-client-linux.md) states that user needs "AWS account root user permissions on the client instance to copy your certificate to this location." However, in this case the user needs the administrative permissions (root user) in the operation system not the AWS root account.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking the time to submit feedback on our documentation. I fixed the error, and public documentation has been updated. 

All best, 
David Ryan
