### ISSUE TITLE
Wrong minimum RSA key size reported by token

### ISSUE THREAD

**Issue by dmjones** [awsdocs/aws-cloudhsm-user-guide#24]
The token reports a minimum supported RSA key of 1024 bits via C_GetMechanismInfo. But it seems like 1024-bits is forbidden by the FIPS settings on the token. The reported minimum should therefore be bigger. (_Not sure where we are supposed to report these kinds of issues_).

Including key sizes in the documentation would also be a good thing.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking the time to submit feedback on our documentation. Since submitting this ticket, this issue has been addressed internally, so the error you experienced shouldn't happen again.

All best,
David Ryan
