### ISSUE TITLE
Add comment to documentation explaining CKA_ID must be unique

### ISSUE THREAD

**Issue by dmjones** [awsdocs/aws-cloudhsm-user-guide#26]
From my experiments, the CKA_ID value must be unique for a key. Or, at least, unique for a given key type (I haven't tested this further).

This should be mentioned somewhere in the documentation. CloudHSM currently returns `CKR_ATTRIBUTE_VALUE_INVALID` when you attempt to create a second key with the same CKA_ID.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking the time to submit feedback on our documentation. Since submitting this ticket, this issue has been addressed internally, so the error you experienced shouldn't happen again.  

All best, 
David Ryan
