### ISSUE TITLE
Add a comment about errors during rapid session creation

### ISSUE THREAD

**Issue by dmjones** [awsdocs/aws-cloudhsm-user-guide#27]
My test code opens a lot of sessions quickly. I've noticed on CloudHSM, this can result in:

```
C_OpenSession failed with error CKR_ARGUMENTS_BAD : 0x00000007
HSM error 8c: HSM Error: Already maximum number of sessions are issued
```

There is a limit being hit here somewhere. Artificially slowing down the code removes the errors.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. It sounds like you actually have a technical support question. If you have [signed up for technical support](https://aws.amazon.com/premiumsupport/), I recommend contacting [technical support](https://aws.amazon.com/contact-us/) for this. You can also post this question on [AWS re:Post](https://repost.aws/), which is a good resource for questions and answers (Q&A).

 All best,
 David Ryan
