### ISSUE TITLE
NGINX does not recognize USR2 signal after cloudhsm ssl engine is enabled.

### ISSUE THREAD

**Issue by mhorbul** [awsdocs/aws-cloudhsm-user-guide#30]
I have added the following directive to the `nginx.conf` file:

```
ssl_engine cloudhsm;
```

SSL termination is offloaded to the CloudHSM and works just fine. But when I send a USR2 signal to Nginx process, nothing happens. 

```
$ kill -USR2 $(cat /var/run/nginx.pid)
```

When I comment out `ssl_engine cloudhsm` directive, and restart nginx it begins to recognize USR2 signal again. It looks like all other signals including QUIT and WINCH work just fine.

I have straced nginx process when USR2 signal is sent to both processes. Here is the result:

NGINX without `ssl_engine` set
```
rt_sigsuspend([])                       = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=23440, si_uid=0} ---
gettimeofday({1570839012, 596258}, NULL) = 0
getppid()                               = 1
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
gettimeofday({1570839012, 596492}, NULL) = 0
rename("/var/run/nginx.pid", "/var/run/nginx.pid.oldbin") = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f180aa89b50) = 6133
rt_sigsuspend([] <detached ...>
```

NGINX with `ssl_engine` set to `cloudhsm`
```
rt_sigsuspend([])                       = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=23440, si_uid=0} ---
gettimeofday({1570838962, 952874}, NULL) = 0
getppid()                               = 1
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
gettimeofday({1570838962, 953140}, NULL) = 0
rename("/var/run/nginx.pid", "/var/run/nginx.pid.oldbin") = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f3e4a531b50) = 5619
rt_sigsuspend([])                       = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5619, si_status=1, si_utime=0, si_stime=0} ---
gettimeofday({1570838962, 960453}, NULL) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], WNOHANG, NULL) = 5619
wait4(-1, 0x7fff59a47b7c, WNOHANG, NULL) = 0
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
gettimeofday({1570838962, 960769}, NULL) = 0
rename("/var/run/nginx.pid.oldbin", "/var/run/nginx.pid") = 0
rt_sigsuspend([] <detached ...>
```

**Comment by ekadoo** [comment]
By default, Nginx removes all environment variables inherited from its parent process except the TZ variable. Therefor new spawned master process does not have `n3fips_password` set and `cloudhsm` SSL engine can not be initialized. In order to address that environment variable `n3fips_password` should be preserved during live upgrades and `env` directive is there for help. http://nginx.org/en/docs/ngx_core_module.html#env

**Comment by mhorbul** [comment]
By default, Nginx removes all environment variables inherited from its parent process except the TZ variable. Therefor new spawned master process does not have n3fips_password set and cloudhsm SSL engine can not be initialized. In order to address that environment variable n3fips_password should be preserved during live upgrades and env directive is there for help. http://nginx.org/en/docs/ngx_core_module.html#env
