### ISSUE TITLE
Initialize the Cluster: clarify .pem permissions, pass phrase

### ISSUE THREAD

**Issue by lhwitherspoon** [awsdocs/aws-cloudhsm-user-guide#32]
In the cluster initialization process, it's not obvious that the pass phrase for the `customerCA.key` is created at that time, rather than earlier. Also, the permissions for the `my-key-pair.pem` file have to be changed beforehand, or the procedure will fail. Have created a pull request to add information to clarify insructions on these two points.

**Comment by lhwitherspoon** [comment]
I've followed instructions to fork the repository and work on that fork. I will find out how I ended up creating this pull request in the master branch.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. We have recently published a major update to CloudHSM documentation (our GitHub code repo has been updated to show this). Consequently, this is no longer an issue.

All best,    
David Ryan
