### ISSUE TITLE
Add info re creating EC2 in getting-started.md

### ISSUE THREAD

**Issue by lhwitherspoon** [awsdocs/aws-cloudhsm-user-guide#34]
Add needed information regarding creating an EC2 to use with the cluster directly in the getting-started.md document on step 3. Users who are already familiar with the EC2 creation process may not read the linked document. Have created a pull request and added in the missing info.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. We have recently published a major update to CloudHSM documentation (our GitHub code repo will soon be updated to show this). Consequently, this is no longer an issue.

All best,    
David Ryan
