### ISSUE TITLE
Key_mgmt_util.exe shows 0kb as the size

### ISSUE THREAD

**Issue by joshiamarpreet** [awsdocs/aws-cloudhsm-user-guide#36]
Key_mgmt_util.exe shows 0kb as the size. I have used a windows instance in AWS. After walking through the system files i see all other files in program files/Amazon/cloudHSM folder. But just the key_mgmt_util.exe file shows 0kb as the size. And when I try to open this file through cmd it shows an error giving “Find a version for your windows”. 

Please help what to do. I tried to re-install the setup but nothing changed.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. It sounds like you actually have a technical support question. If you have signed up for technical support (https://aws.amazon.com/premiumsupport/), I recommend contacting support for this. You can also post this question on AWS re:Post, which is a good resource for questions and answers (Q&A).

All best,
David Ryan
