### ISSUE TITLE
Please remove the bullet pertaining to "Vormetric Data Security Platform"

### ISSUE THREAD

**Issue by cyberswimmer** [awsdocs/aws-cloudhsm-user-guide#38]
Circumstances forced us to stop the project adding support for AWS Cloud HSM from the Vormetric Data Security Platform.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking the time to submit feedback on our documentation. I fixed removed the bullet point and public documentation will soon be updated. 

All best, 
David Ryan
