### ISSUE TITLE
Remove/change password for logged in user

### ISSUE THREAD

**Issue by ghost** [awsdocs/aws-cloudhsm-user-guide#40]
It's not the first case when we can't reset password for logged in user:
```
aws-cloudhsm>changePswd CU user pass
*************************CAUTION********************************
This is a CRITICAL operation, should be done on all nodes in the
cluster. AWS does NOT synchronize these changes automatically with the 
nodes on which this operation is not executed or failed, please 
ensure this operation is executed on all nodes in the cluster.  
****************************************************************

Do you want to continue(y/n)?y
Changing password for user (CU) on 1 nodes
changePswd failed: HSM Error: Deletion or Changing password of a logged in User is denied
Changing password on node 0(10.11.12.13) failed

Retry/Ignore/Abort?(R/I/A):A
```
The same problem for removing.

I've tried to do that later for billion times. Is it possible to overcome this problem? I mean for example to force logout for that user or at least to find from where that session is?

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. It sounds like you actually have a technical support question. If you have [signed up for technical support](https://aws.amazon.com/premiumsupport/), I recommend requesting [technical support](https://aws.amazon.com/contact-us/) for this. You can also post this question on [AWS re:Post](https://repost.aws/), which is a good resource for questions and answers (Q&A).

 All best,
 David Ryan
