### ISSUE TITLE
Question about SSL/TLS Offload on Windows

### ISSUE THREAD

**Issue by szl0144** [awsdocs/aws-cloudhsm-user-guide#43]
Hi,
OS: Microsoft Windows Server 2019 Datacenter.
CloudHSM Client: https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/Windows/AWSCloudHSMClient-latest.msi

I generate a private key and CSR using cloudhsm engine in a Linux client. I find a CA sign the CSR and get a certificate (Without private Key). I am going to install the certificate in a Windows Server. I tried following ways to install the certificate but all failed. Can you please help me on it?

1) Follow the instruction directly: C:\>certreq -accept IISCert.crt (https://docs.aws.amazon.com/cloudhsm/latest/userguide/ssl-offload-configure-web-server-windows.html). It seems my Windows server can't find the private key.

So I try to 2) associate an AWS CloudHSM key with my certificate (https://docs.aws.amazon.com/cloudhsm/latest/userguide/ksp-library-associate-key-certificate.html), but I can't open the import_key.exe file in CMD. It shows This app can't run on my PC.  
![image](https://user-images.githubusercontent.com/40918217/119900753-ee1b1180-bf12-11eb-92a8-6add59ea192b.png)

Then I try to use the third way. I merge the fake PEM private key generated from CloudHSM with the certificate signed by CA. I import the certificate into the IIS server and set it in the Service site binding, but I can't  load the certificate and face an error there was an error while performing this operation A specified logon session does not exst it may already have been terminated.
![image](https://user-images.githubusercontent.com/40918217/119901517-02134300-bf14-11eb-8129-112b5d9be784.png)

I don't know how to solve the problem, can you please give me some help? Thanks!

Best,
Shaoyi

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. It sounds like you actually have a technical support question. If you have signed up for technical support (https://aws.amazon.com/premiumsupport/), I recommend [contacting support](https://aws.amazon.com/contact-us/) for this. You can also post this question on [AWS re:Post](https://repost.aws/), which is a good resource for questions and answers (Q&A).

 All best,
 David Ryan
