### ISSUE TITLE
Need java sample code for AWS CloudHSM PKCS11 library

### ISSUE THREAD

**Issue by nitin83garg19** [awsdocs/aws-cloudhsm-user-guide#44]
I am integrating the AWS CloudHSM PKCS11 library with our JAVA based application. My application supports standard SunPKCS11 library, where we pass the PKCS11 configuration parameters like 'library, slot, name etc'. The AWS CloudHSM documentation having only the 'C' sample code. It would be great if you could provide the 'Java' sample code for PKCS11 provider.

Below is the code which i am using to create keys in AWS CloudHSM:

**Config File:**

```
name = cloudHSM
library = /opt/cloudhsm/lib/libcloudhsm_pkcs11.so
slot = 0
attributes(generate, *, *) = {
   CKA_TOKEN = true
}
```

**Java code:**

```
String configName = "pkcs11.cfg";
Provider p = new SunPKCS11(configName);
if (-1 == Security.addProvider(p)) {
         throw new RuntimeException("could not add security provider");
}

// Load the key store
char[] pin = "<CU_user_name>:<password>".toCharArray();
KeyStore keyStore = KeyStore.getInstance("PKCS11", p);
keyStore.load(null, pin);
KeyGenerator kgen = KeyGenerator.getInstance("AES"); 

```

**Comment by dmryan123** [comment]
Hello,

Thank you for taking the time to submit feedback on our documentation. We have recently published a major update to CloudHSM documentation (our GitHub code repo has been updated to show this). Consequently, this is no longer an issue.   

All best, 
David Ryan
