### ISSUE TITLE
Does not document Ubuntu 20.04

### ISSUE THREAD

**Issue by rrileyar** [awsdocs/aws-cloudhsm-user-guide#45]
Amazon is currently shipping with Ubuntu 20.04, this does not provide a link to the appropriate "focal" download.

**Comment by dmryan123** [comment]
Hello,

Thank you for providing feedback on this. AWS CloudHSM currently does not support Ubuntu 20.04. But I will leave this issue open for the time being and see what additional information I can find on this topic. 

All best, 
David Ryan

**Comment by ddaws** [comment]
@dmryan123 why isn't 20.04 supported? Or what needs to be done to support 20.04?

**Comment by dmryan123** [comment]
Hi Dawson, 

Great question. I'll meet with the team next week to discuss support for Ubuntu 20.04. I'll follow up next week with my findings.

All the best, 
David

**Comment by ddaws** [comment]
Thanks! Are the CLI tools open source? I haven't been able to find them, but if they are I'd be up for contributing :)

**Comment by ddaws** [comment]
Hey @dmryan123, just following up. Any update here?

**Comment by dmryan123** [comment]
Hi Dawson,

Unfortunately, our CLI tools are not open source, but I will have an update on Ubuntu 20.04 tomorrow. 

Thank you, 
David

**Comment by dmryan123** [comment]
Hi Dawson,

CloudHSM just released Client SDK 5.6, which supports Ubuntu 20.04. So this issue should be resolved. For more information, refer to the latest version of Client SDK 5 in [Download AWS CloudHSM Client SDK](https://docs.aws.amazon.com/cloudhsm/latest/userguide/client-history.html).

All the best, 
David
