### ISSUE TITLE
The KMU "singlecmd" is not documented in the reference section

### ISSUE THREAD

**Issue by ddaws** [awsdocs/aws-cloudhsm-user-guide#46]
Several resource imply there is a `singlecmd` command that is useful for scripting interactions with CloudHSM but this isn't documented in the [KMU command reference here](https://docs.aws.amazon.com/cloudhsm/latest/userguide/key_mgmt_util-reference.html). It would be great to get documentation on how to use this. 

Here are some examples of references to `singlecmd`

- https://aws.amazon.com/premiumsupport/knowledge-center/cloudhsm-import-keys-openssl/
- https://docs.aws.amazon.com/cloudhsm/latest/userguide/key_mgmt_util-genSymKey.html
- https://youtu.be/_gezaWmwzYY?t=1921 <-- 2019 AWS re:Inforce presentation 

Each of these docs show `singlecmd` being used in slightly different ways, and it's not clear from any of these if there is a way to authenticate to the CloudHSM without providing a password in plan text. It would be great to get documentation on best practices for using `singlecmd`

**Comment by ddaws** [comment]
@dmryan123 any update here would be appreciated :pray: I'd like to script some of my CloudHSM setup and make sure I am doing it the right way.

**Comment by dmryan123** [comment]
Hi Dawson, 

Thanks for the feedback and for following up on this. I have a meeting scheduled with the CloudHSM team to discuss this topic. I'll follow up early next week to let you know how it turns out. 

All best, 
David

**Comment by dmryan123** [comment]
Hi Dawson,

Thanks again for taking the time to provide feedback. This request has been received by the CloudHSM team and will be added to the queue. They will scope it out and prioritize it. For information on authenticating to the CloudHSM without providing a password in plain text, I recommend reaching out to AWS technical support (https://aws.amazon.com/premiumsupport/). Additionally, you can post questions on AWS re:Post (https://repost.aws/), which is a good resource for questions and answers (Q&A). 

All the best, 
David

**Comment by ddaws** [comment]
Okay, thanks @dmryan123. Can we keep this issue open until the documentation is updated?

**Comment by dmryan123** [comment]
Hi Dawson,

I hope all is well. I'll leave the ticket open for visibility. 

All the best, 
David

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
