### ISSUE TITLE
No import mechanisms in "Generate, Create, Import Keys" section

### ISSUE THREAD

**Issue by dmjones** [awsdocs/aws-cloudhsm-user-guide#5]
The PKCS#11 library page has a section:

> **Generate, Create, Import Keys**
> * `CKM_AES_KEY_GEN`
> * `CKM_DES3_KEY_GEN`
> * `CKM_EC_KEY_PAIR_GEN`
> * `CKM_GENERIC_SECRET_KEY_GEN`
> * `CKM_RSA_X9_31_KEY_PAIR_GEN`

I'm not a PKCS #11 expert, but I don't believe any of these mechanisms can be used to import keys.

As far as I can tell from reading that page, the only way to import keys is to unwrap them using `C_UnWrapKey` and `CKM_AES_KEY_WRAP`, or use `C_CreateObject` (for public keys, presumably).

**Comment by juneb** [comment]
Sorry for the slow reply! Yes, I think you're right. Let me chat with the engineering team.

**Comment by dmryan123** [comment]
Hello,

Thank you for taking time to submit feedback on our documentation. It sounds like you actually have a technical support question. If you have [signed up for technical support](https://aws.amazon.com/premiumsupport/), I recommend contacting [technical support](https://aws.amazon.com/contact-us/) for this. You can also post this question on [AWS re:Post](https://repost.aws/), which is a good resource for questions and answers (Q&A).

 All best,
 David Ryan
