### ISSUE TITLE
Needs more information on PKCS#11 token/slot layout

### ISSUE THREAD

**Issue by dmjones** [awsdocs/aws-cloudhsm-user-guide#7]
It would be great to have some more information about how Cloud HSM presents slots and tokens to the user. Probably this deserves a separate (small) page in the PKCS#11 section.

As a bare minimum, it would be useful to know what label to expect on the token. Or perhaps some reassurance that there is only one slot, and that slot definitely contains the right token (whatever the label is).

It would also be useful to know whether applications using different HSMs in the same cluster will see the same label / slot layout / identifying information.

**Comment by dmjones** [comment]
From my experimentation, it seems like only one slot is presented, containing a token labelled "cavium". This is my experience, at least, when using a client configured with two HSMs in a cluster.

**Comment by joshbean** [comment]
Thanks for the feedback, @dmjones. We'll consider adding more content to explain the PKCS#11 interface for AWS CloudHSM. In the meantime, if you have the time or interest in drafting something up and submitting a PR, we'll gladly consider that, too.

**Comment by tulsidas** [comment]
I agree with this. There's a lacking in documentation for PKCS#11 in general.

**Comment by nitin83garg19** [comment]
@joshbean, I am integrating the AWS cloudHSM PKCS11 library with our JAVA based application. My application supports standard SunPKCS11 library, where we pass the PKCS11 configuration parameters like 'library, slot, name etc'. The AWS cloudHSM documentation having only the 'C' sample code. It would be great if you could provide the 'Java' sample code for PKCS11 provider.

**Comment by nklaassen** [comment]
I could not find any information on the SDK v5 slot layout. For now I discovered a single slot labelled "hsm1" but I have no idea if that's consistent or what it will be if I create more than 1 hsm

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
