### ISSUE TITLE
cloudhsm.so file not found error

### ISSUE THREAD

**Issue by NisariAIT** [awsdocs/aws-cloudhsm-user-guide#8]
I am trying to offload SSL processing to CloudHSM. The web server is an nginx server.  While trying to configure the web server by adding

 `ssl_engine cloudhsm;`

this error is received in the error log and nginx does not get restarted:

`2018/05/30 09:02:50 [emerg] 5429#0: ENGINE_by_id("cloudhsm") failed (SSL: error:25066067:DSO support routines:dlfcn_load:could not load the shared library:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/cloudhsm.so): /usr/lib/x86_64-linux-gnu/engines-1.1/cloudhsm.so: cannot open shared object file: No such file or directory error:25070067:DSO support routines:DSO_load:could not load the shared library error:260B6084:engine routines:dynamic_load:dso not found error:2606A074:engine routines:ENGINE_by_id:no such engine:id=cloudhsm)`

The cloudhsm.so file is not present at the location. Is there any library that needs to be installed to solve this?

**Comment by joshbean** [comment]
Hello @NisariAIT!

Sorry for the delayed response. Here are a few things you can try:
1. [Install and Configure the OpenSSL Dynamic Engine](https://docs.aws.amazon.com/cloudhsm/latest/userguide/openssl-library-install.html#install-openssl-library) (if you haven't already)
2. [Start the AWS CloudHSM Client](https://docs.aws.amazon.com/cloudhsm/latest/userguide/cloudhsm_mgmt_util-getting-started.html#cloudhsm_mgmt_util-start-cloudhsm-client) (if you haven't already)
3. Make sure you've set the `n3fips_password` environment variable (step 9 in [this procedure](https://docs.aws.amazon.com/cloudhsm/latest/userguide/ssl-offload-configure-web-server.html#update-web-server-config-nginx))

I hope this helps!

**Comment by NisariAIT** [comment]
Hi @joshbean,
I am getting this when I execute the openssl engine command. And n3fips_password is not getting set. Could you please tell me how to set the password. I am not able to find the sysconfig file. I am on an ubuntu server with nginx.
![image](https://user-images.githubusercontent.com/36888737/41189514-b517109a-6bec-11e8-8859-2a28e796c728.png)
Thanks!

**Comment by joshbean** [comment]
Hi @NisariAIT 

It looks like the AWS CloudHSM dynamic engine for OpenSSL is working (indicated by "SDK Version: 2.03" in the output). To set the `n3fips_password` environment variable on a Linux system, complete step 3 in the [OpenSSL engine installation steps](https://docs.aws.amazon.com/cloudhsm/latest/userguide/openssl-library-install.html#install-openssl-library). On a Linux system, you use the following command, replacing `<HSM user name>` and `<password>` with the actual user name and password of a [crypto user (CU)](https://docs.aws.amazon.com/cloudhsm/latest/userguide/hsm-users.html#crypto-user) on the HSM.

`export n3fips_password=<HSM user name>:<password>`

**Comment by NisariAIT** [comment]
Thanks @joshbean , 
I tried to set the environment variable using the export command and after contacting AWS support found that for my configuration(nginx compiled from source), I had to create sysconfig/nginx file at /etc and add
`n3fips_password=<HSM user name>:<password>`
in it and add environment variable path to nginx.service file to get set this working.

**Comment by joshbean** [comment]
Hi @NisariAIT ,

Thanks for following up with the additional details. I'm glad you were able to get this working in your environment. This sounds like something that we could potentially add to the [troubleshooting section of the CloudHSM docs](https://github.com/awsdocs/aws-cloudhsm-user-guide/blob/master/doc_source/troubleshooting.md). I'll keep this issue open so we don't lose track of it.

**Comment by NisariAIT** [comment]
Hi @joshbean 
I had to change one more thing: I was using openSSL version 1.1.0 and CloudHSM support is available only up to 1.0.2. I had to compile nginx with openssl 1.0.2 to get cloudHSM working. 
It could be great if we could know when CloudHSM support will be available for OpenSSL 1.1.0 as we can use more secure ciphers for SSL handshake with 1.1.
